name: IllamaGrades
main: com.example.illamagrades.IllamaGrades
version: 1.0
api-version: 1.20
commands:
  setitem:
    description: Définit la permission pour un item
    usage: /<command> <item> <permission> [world]
permissions:
  illamagrades.setitem:
    description: Permission to change the item
    default: op